[[headers]]
    for = "/*"
    [headers.values]
        X-Frame-Options = "deny"
        X-XSS-Protection = "1"
        Cache-Control = "max-age=0"
        X-Content-Type-Options = "nosniff"
        Keep-Alive = "100"
        Connection = "keep-alive"
        Referrer-Policy = "no-referrer"
        
        Strict-Transport-Security = '''
            max-age=31557600;
            includeSubDomains;
            preload
        '''

        Permissions-Policy = '''
            interest-cohort=(none)
        '''
